---
title: "grid_plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(scales)
library(tidyverse)
library(cowplot)

theme_set(theme_cowplot())

source("../../common/simulation.R")
```

```{r}

copy_obs <- function(single_sample){
  
  single_sample_edge_copies <- 
    rbind(
      single_sample %>% mutate(obs_degree = obs_degree - 360),
      single_sample,
      single_sample %>% mutate(obs_degree = obs_degree + 360)
    )
}

plot_cdf <- function(c1, c2){
  
  ggplot + 
    c1 + c2 + 
    scale_x_continuous(breaks = pretty_breaks(12))  + 
    scale_y_continuous(breaks = seq(0, 1, 0.25)) + 
    coord_cartesian(xlim=c(-180, 180), expand = FALSE) + 
    expand_limits(y = 0)
}

parameters <- 
  cross_df(
    list(
      pMem = seq(0, 1, 0.1),
      sd = seq(5, 130, 5)
    )
  ) %>%
  mutate(k = sd2k_vec(pracma::deg2rad(sd)))


cdfs <- 
  parameters %>%
    mutate(sim = pmap(parameters %>% select(-sd), simulateData_likelihood, nobs = 2e3),
           tag = pmap(parameters, ~ glue::glue("pMem{.x}_sd{.y}")),
           sim_cdf = map(sim, ~ stat_ecdf(data = ., aes(x = obs_degree), size = 1)))

t1 <- "pMem0.6_sd75"
t2 <- "pMem0.6_sd60"

ggplot() + 
  unlist(cdfs %>% filter(tag == t1) %>% select(sim_cdf)) + 
  unlist(cdfs %>% filter(tag == t2) %>% select(sim_cdf)) + 
  geom_hline(yintercept = seq(0, 1, 0.25), linetype = "dashed", alpha = 0.2) + 
  scale_x_continuous(breaks = pretty_breaks(12))  + 
    scale_y_continuous(breaks = seq(0, 1, 0.25)) + 
    coord_cartesian(xlim=c(-180, 180), expand = FALSE) + 
    expand_limits(y = 0) + 
  labs(y = "cumulative probability") 

ggplot() + 
  geom_histogram(data = cdfs %>% filter(tag == t1) %>% select(sim) %>% unnest(sim), aes(x = obs_degree), binwidth = 10)


```

